# Linguagem Utilizada para Desenvolver a Aplicação                                                                                                                                                       
language: python                                                                                                                                                                                         

# Versão que a aplicação suporta.                                                                                                                                                                        
python:                                                                                                                                                                                                  
  - "3.7.9"                                                                                                                                                                                              

#Build Environments
os: linux
dist: xenial

# Instalação de Módulos que são necessários para a Aplicação.                                                                                                                                            
install:                                                                                                                                                                                                 
  - pip install flask flask-wtf coverage

addons:                                                                                                                                           
  sonarcloud:                                                                                                                                     
    organization: gabydias-github                                                                                                                 
    token: ${SONAR_TOKEN}

# Defini o script de Teste que deve rodar toda vez que o código for alterado.                                                                                                                            
script:                                                                                                                                                                                                  
  - python -m unittest -v test || travis_terminate 1;
  - coverage report app.py || travis_terminate 1;
  - coverage xml app.py || travis_terminate 1;
  - sonar-scanner || travis_terminate 1;

# Definir o Deploy no Heroku
deploy:
  provider: heroku
  strategy: api
  api_key: $HEROKU_API_KEY
  edge: true 
  app: devopslabs-gabriela
  on:
      branch: main
